require: rubocop-rails

AllCops:
  Exclude:
    - Gemfile
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2

Gemspec/DateAssignment:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DateAssignment:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Rails/EnumUniqueness:
  Exclude:
    - 'app/models/pto/type_policy.rb'
    - 'app/models/pto/absence.rb'
Rails/ActiveRecordAliases:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'services/*/specs/**/*_spec.rb'
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'services/*/specs/**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_ignore

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Semicolon:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'services/*/specs/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
    - 'services/*/specs/**/*'
    - '**/*.rake'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  Enabled: false

# This replaces the old Style/Blocks. The default for this is still stupid
# (multiline blocks are do/end and single-line blocks are {/}), but it now
# performs a semantic analysis, allowing for the more nuanced version proposed
# by Jim Weirich around 2004. If a block is used as part of an assignment or
# method chaining, prefer {/} delimiters; if not, prefer do/end delimiters. It
# isn't *quite* that simple in all circumstances, but we can add them to one of
# three groups: ProceduralMethods (prefer do/end), FunctionalMethods ({/}), and
# ignored (because it does not matter).
Style/BlockDelimiters:
  Enabled: false
  EnforcedStyle: semantic
  Exclude:
    - '**/*factory.rb'
  ProceduralMethods:
    # Methods that are known to be procedural in nature but look functional from
    # their usage, e.g.
    #
    #   time = Benchmark.realtime do
    #     foo.bar
    #   end
    #
    # Here, the return value of the block is discarded but the return value of
    # `Benchmark.realtime` is used.
    - benchmark
    - bm
    - bmbm
    - create
    - each_with_object
    - measure
    - new
    - realtime
    - tap
    - with_object
    - assert_raises
    - solr_search
    - solr_paginated
    - all_of
    - any_of
  FunctionalMethods:
    # Methods that are known to be functional in nature but look procedural from
    # their usage, e.g.
    #
    #   let(:foo) { Foo.new }
    #
    # Here, the return value of `Foo.new` is used to define a `foo` helper but
    # doesn't appear to be used from the return value of `let`.
    - let
    - let!
    - subject
    - watch
  IgnoredMethods:
    # Methods that can be either procedural or functional and cannot be
    # categorised from their usage alone, e.g.
    #
    #   foo = lambda do |x|
    #     puts "Hello, #{x}"
    #   end
    #
    #   foo = lambda do |x|
    #     x * 100
    #   end
    #
    # Here, it is impossible to tell from the return value of `lambda` whether
    # the inner block's return value is significant.
    - lambda
    - proc
    - it
    - around
    - before

Style/FormatString:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/RedundantPercentQ:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line
  Severity: convention

Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/LineLength:
  Max: 100
  Exclude:
    - test/**/*
    - db/migrate/**/*
    - app/admin/**/*

Layout/SpaceBeforeBrackets:
  Enabled: true

Style/MethodDefParentheses:
  Exclude:
    - test/**/*

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'services/*/specs/**/*_spec.rb'

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRange:
  Enabled: true

Lint/BigDecimalNew:
  AutoCorrect: true
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Severity: convention

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/SymbolConversion:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessRuby2Keywords:
  Enabled: true

# Migration/DepartmentName:
#   Enabled: false

Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: consistent

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true
  Max: 1

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
